"""made category nullable

Revision ID: 3741aadaf172
Revises: a59ca783570e
Create Date: 2025-12-21 14:51:09.622069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3741aadaf172'
down_revision = 'a59ca783570e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('event_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('fk_post_category',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('fk_post_category',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('event_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
